### ISSUE TITLE
USER STORY: Create main storyline

### ISSUE THREAD

**Issue by stephendawsondev** [stephendawsondev/jedi-academy#5]
### If applicable, add a related Epic.

EPIC: Interactive Storyline

### User Story

As a player, I want to experience an engaging Star Wars storyline so that I can make choices and affect the outcome.

### Acceptance Criteria

- Storyline is written
- Decision points are included
- Multiple endings are possible

### Please ensure you've completed these tasks before marking the issue as done.

- [x] Reviewed the user story for clarity and completeness.
- [ ] Updated the issue with any relevant notes or feedback (to date).

### Please add any further tasks that need to be completed before the issue can be marked as done.

- [x] Write main storyline
- [ ] Define decision points
- [ ] Implement multiple endings

**Comment by donald-macritchie** [comment]
main story and pathway is done

**Comment by donald-macritchie** [comment]
linked pull request #22

**Comment by stephendawsondev** [comment]
@donald-macritchie Can this be closed as complete or are there still things to add to the story?
