### ISSUE TITLE
USER STORY: Source sound clips

### ISSUE THREAD

**Issue by stephendawsondev** [stephendawsondev/jedi-academy#8]
### If applicable, add a related Epic.

EPIC: Sound and Visual Assets

### User Story

As a team, we need to source Star Wars sound clips so that we can enhance the game's audio experience.

### Acceptance Criteria

- Sound clips are sourced
- Clips are relevant and high-quality
- Clips are integrated into the game

### Please ensure you've completed these tasks before marking the issue as done.

- [x] Reviewed the user story for clarity and completeness.
- [x] Updated the issue with any relevant notes or feedback (to date).

### Please add any further tasks that need to be completed before the issue can be marked as done.

- [x] Find sound clips
- [x] Ensure clips are high-quality
- [x] Integrate clips into the game

**Comment by creepersguitar** [comment]
found sound clips for c3p0, jar jar binks (whack a jar jar game), yoda (congrats for becoming a jedi master and beating sidious as well as intro clip for when you start the story) and i have found the embed code for if we just want to add it straight into the HTML code
